server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: product-service-api
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: product-service-docs
          uri: lb://product-service
          predicates:
            - Path=/product-service/v3/api-docs/**
        - id: product-service-ui
          uri: lb://product-service
          predicates:
            - Path=/product-service/swagger-ui/**
        - id: booking-service-api
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: booking-service-docs
          uri: lb://booking-service
          predicates:
            - Path=/booking-service/v3/api-docs/**
        - id: booking-service-ui
          uri: lb://booking-service
          predicates:
            - Path=/booking-service/swagger-ui/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-server:8080/realms/application-realm
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak-server:8080/realms/application-realm
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: springsecret123
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/spring-cloud-gateway-client"
            scope: openid, profile, email

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url.defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    urls:
      - name: product-service
        url: /product-service/v3/api-docs
      - name: booking-service
        url: /booking-service/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true