server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
        - Path=/api/products/**
        - id: product-swagger
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**
        - id: booking-swagger
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking-service/v3/api-docs/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-server:8080/realms/application-realm
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak-server:8080/realms/application-realm
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: springsecret123
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/spring-cloud-gateway-client"
            scope: openid, profile, email

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url.defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"