spring:
  datasource:
    url: jdbc:mysql://mysql_database:3306/booking_db
    username: root
    password: A8424628
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8082