spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    username: root
    password: A8424628
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true